'use strict';

const nodemailer = require('nodemailer');

/**
 * Format a field value for display in email.
 * @param {*} v
 * @returns {string}
 */
function fmtValue(v) {
  if (v === null || v === undefined) return '<em>null</em>';
  if (Array.isArray(v)) return v.length === 0 ? '<em>empty</em>' : v.join('<br>');
  return String(v);
}

/**
 * Format a field value for plain-text email.
 * @param {*} v
 * @returns {string}
 */
function fmtValueText(v) {
  if (v === null || v === undefined) return '(null)';
  if (Array.isArray(v)) return v.length === 0 ? '(empty)' : v.join(', ');
  return String(v);
}

/**
 * Build the HTML body for the email.
 * @param {object[]} changed  - diff records with changed: true
 * @param {string}   date
 * @returns {string}
 */
function buildHtml(changed, date) {
  const sections = changed.map(r => {
    const rows = r.fields_changed
      .map(
        field => `
      <tr>
        <td style="padding:4px 8px;border:1px solid #ccc;font-family:monospace">${field}</td>
        <td style="padding:4px 8px;border:1px solid #ccc;color:#c00">${fmtValue(r.diff[field].before)}</td>
        <td style="padding:4px 8px;border:1px solid #ccc;color:#060">${fmtValue(r.diff[field].after)}</td>
      </tr>`
      )
      .join('');

    const firstSeenNote = r.first_seen
      ? `<p><em>First seen today — no prior snapshot.</em></p>`
      : '';

    return `
    <h3 style="margin-top:24px">${r.domain}</h3>
    ${firstSeenNote}
    <table style="border-collapse:collapse;font-size:13px">
      <thead>
        <tr>
          <th style="padding:4px 8px;border:1px solid #ccc;background:#f5f5f5">Field</th>
          <th style="padding:4px 8px;border:1px solid #ccc;background:#f5f5f5">Before</th>
          <th style="padding:4px 8px;border:1px solid #ccc;background:#f5f5f5">After</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`;
  });

  return `
<!DOCTYPE html>
<html>
<body style="font-family:sans-serif;color:#222;max-width:800px;margin:auto;padding:16px">
  <h2>Epik WHOIS Watcher — ${changed.length} domain(s) changed on ${date}</h2>
  ${sections.join('\n')}
  <hr style="margin-top:32px">
  <p style="font-size:11px;color:#888">Generated by epik-watcher</p>
</body>
</html>`;
}

/**
 * Build the plain-text fallback body.
 * @param {object[]} changed
 * @param {string}   date
 * @returns {string}
 */
function buildText(changed, date) {
  const lines = [
    `Epik WHOIS Watcher — ${changed.length} domain(s) changed on ${date}`,
    '='.repeat(60),
    '',
  ];

  for (const r of changed) {
    lines.push(`DOMAIN: ${r.domain}`);
    if (r.first_seen) lines.push('(First seen today — no prior snapshot)');
    lines.push('-'.repeat(40));
    for (const field of r.fields_changed) {
      lines.push(`  ${field}:`);
      lines.push(`    Before: ${fmtValueText(r.diff[field].before)}`);
      lines.push(`    After:  ${fmtValueText(r.diff[field].after)}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Send an email alert if any domains changed.
 *
 * @param {object[]} results  - all diff records
 * @param {string}   date     - YYYY-MM-DD
 * @param {object}   config
 * @returns {Promise<{sent: boolean, recipients: string[], error: string|null}>}
 */
async function sendChangeAlert(results, date, config) {
  const emailCfg = config.email || {};

  if (!emailCfg.enabled) {
    return { sent: false, recipients: [], error: null };
  }

  const changed = results.filter(r => r.changed);
  if (changed.length === 0) {
    return { sent: false, recipients: [], error: null };
  }

  const recipients = Array.isArray(emailCfg.to) ? emailCfg.to : [emailCfg.to];

  try {
    const transporter = nodemailer.createTransport({
      host: emailCfg.smtp_host,
      port: emailCfg.smtp_port,
      secure: emailCfg.smtp_port === 465,
      auth: {
        user: emailCfg.smtp_user,
        pass: emailCfg.smtp_pass,
      },
    });

    await transporter.sendMail({
      from: emailCfg.from,
      to: recipients.join(', '),
      subject: `[epik-watcher] ${changed.length} domain(s) changed — ${date}`,
      text: buildText(changed, date),
      html: buildHtml(changed, date),
    });

    return { sent: true, recipients, error: null };
  } catch (err) {
    return { sent: false, recipients, error: err.message };
  }
}

module.exports = { sendChangeAlert };
